### ISSUE TITLE
Different approach?

### ISSUE THREAD

**Issue by dmaicher** [facile-it/paraunit-testcase#13]
First of all: Interesting approach with this bundle :wink: :+1: 

I developed something similar that seems to be easier to integrate & use: https://github.com/dmaicher/doctrine-test-bundle

Let me know what you think about my solution.

**Comment by Jean85** [comment]
Thanks!
Your approach seems interesting too. It's easier than mine, but I think that my testcase solves some additional case, like handling the Symfony client for functional tests. In there, since I extend the Liip bundle, I have additional performance boost due to the fact that I avoid restarting the kernel, but I have to write some workaround to that (see submitting forms with EntityType fields, for example).

**Comment by dmaicher** [comment]
Ah ok I see :wink: 

Seems a bit tricky though to not restart the kernel in between requests as technically the app can behave different in functional tests than with requests via a normal webserver. So tests might pass but actually something might not be working as expected when deploying.

But if it works for you then good :+1:

**Comment by Jean85** [comment]
Well, the client (which extends Symfony's) has an helper method to request a restart of the kernel in between requests, which is the workaround (for i.e. EntityType fields) that I was talking about.

Still, this is needed when some piece of code is not stateless, but I think that this kind of behavior is bad until absolutely needed...
